### PR TITLE
Feature 2

### PR DESCRIPTION
**Pull request by AndreLau11**
adding more style

### CODE REVIEW

**Review by micheaol — CHANGES_REQUESTED** [review]
Hi @AndreLau11 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## TO HIGHLIGHT: 
- Your project is professional 💯 
- Your repo is professional 💯 
- Well structured files 💯 

## Required Changes ♻️

- Please ensure that Linter is set up correctly for this repository. Please check this [LINK](https://github.com/microverseinc/linters-config/tree/master/html-css) for help.
- Please ensure to add test.md file with the text "This file should be ignored by git

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Comment by AndreLau11** [comment]
@micheaol I just fixed the line 2 and 3 fo your comments, are those the only error or you added more in another area? I did not understand the first line of your comments, below your feedback:

Check the comments under the review._
Please ensure that Linter is set up correctly for this repository. Please check this [LINK] for help. (done)
Please ensure to add test.md file with the text "This file should be ignored by git (done)

**Comment by micheaol** [comment]
@AndreLau11 , please check the comment again. Once you have fixed the requested changes in the comment. Please resubmit for review. If you have any other questions, please contact me.

**Review by ShoiraTa — APPROVED** [review]
### **STATUS: APPROVED  ✔️** 
------
Hi @AndreLau11 ,  

Your project is complete! Congratulations!  🎉💯🌟 

## Good Points 👍 
- Project is set up correctly ✔️ 
- Descriptive Pull Request ✔️ 
- No linter errors ✔️ 
- Professional documentation ✔️ 



### OPTIONAL 

- [ ] OPTIONAL: I have noticed that you have already committed most of the files into main, like index.html, test.md and readme this is wrong approach. In the future please do  not commit any file (except initial empty `readme`) before reviewers approval. 

Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀 

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
